### ISSUE TITLE
Super fast cursor, not in sync with hand position, since last DCS update

### ISSUE THREAD

**Issue by fisadev** [glenmurphy/fingers#12]
Hi!

Since yesterday's DCS update, the cursor is moving way too fast compared to my hands. Before it  was perfect, but now if I move my real finger a few cms, the virtual cursor inside the DCS cockpit moves around the entire screen.

Something must have changed in DCS, but I can't find any cursor movement speed setting to tune and try to fix it on that side. Is there anything you know I could try, or something I could configure in the Fingers app instead? Does it happen to you too?

Thanks for the help! And for the app, it's super useful, I've been flying for it all the time :)

**Comment by glenmurphy** [comment]
Just tried the new DCS update and didn't notice any difference - for me it works the same as before. I wonder if it could be something to do with screen resolution or monitor setup? The cursor movement is based on how big the DCS window is on your desktop. Do you have any special configurations there?

**Comment by fisadev** [comment]
Ok, in my case my screen resolution is 1920x1080, and DCS runs at that resolution in the desktop and at the headset resolution in the headset... except I'm using both foveated rendering and upscaling (90%) from OpenXR Toolkit. Maybe that could be the issue?

That's something I just recently started using. So I wouldn't discard the possibility of the sensitivity being broken since then, and me just realizing it last night after the update. I'll try disabling them and share my results (both in case that's the cause so others can find this, or if that wasn't the case so to rule out causes).

**Comment by fisadev** [comment]
Update:
The foveated rendering and upscaling definitely have an impact. Disabling both settings the cursor movement is closer to feeling "normal", though I still feel it "faster than my real hand". Maybe before using those features I simply didn't notice it because it wasn't so bad. And now that I noticed it, I see it even when it's not that bad.

It would be nice if we could calibrate the movement in some way. Maybe a multiplier that we can set in some config file, for each axis, so we can slow down or speed up the movement at will?

**Comment by glenmurphy** [comment]
The issue is (and I am daft for not realizing this earlier) the different horizontal FOVs of different headsets. Will add a FOV control.

**Comment by fisadev** [comment]
Makes sense! And sometimes the most obvious things are the hardest ones to notice, specially in code hehe.
