### ISSUE TITLE
Calibration Problem

### ISSUE THREAD

**Issue by Blender-Alien** [glenmurphy/fingers#3]
Hi,

I ran into a problem, where my movements are vertically translated correctly but my mouse is way off to the right,
making it unusable.

Is there any sort of calibration I can do?

Thanks

**Comment by glenmurphy** [comment]
Fingers doesn't have left/right calibration - but a few questions to help debug:
- Do you have multiple monitors? Currently fingers *should* only be using the dimensions of the monitor DCS is on, but it's possible its reading the size of all the monitors together and centering based on that. If you swap the position of the monitors or disable one before starting Fingers, does that change where the cursor is?
- Is your DCS window centered? It should center itself, but maybe there are situations where it doesn't?

**Comment by Blender-Alien** [comment]
Hi,

I do have 2 Monitors. I'll try disabling my second one. Dcs is perfectly center. I figured out that the app moves my Cursor around in a Box matching the Size of my dcs window, but aligned at the right bottom of my dcs monitor. Switching dcs to Windowed and placing it at the bottom right Kind of makes it work, but it's still at Bit too much to the right.

Kind regards

**Comment by guilbaults** [comment]
I had the same problems on a setup with 3x 1920x1080 screens with DCS in the primary/middle screen.

SetCursorPosition should receive 1920/2 to be centered in the middle and primary screen, but by using the VirtualScreen dimensions, it receive the position at (3*1920)/2 and this end up at the far right of the window and the cursor is stuck there.

Here is the patch:
https://github.com/glenmurphy/fingers/pull/4

**Comment by glenmurphy** [comment]
Flight delays mean my brain is a bit fuzzy, but in the interest of getting you going quickly, here is a test build with [guilbaults](https://github.com/guilbaults) fix - let me know if it works for you:

[fingers_primarymon.zip](https://github.com/glenmurphy/fingers/files/10388658/fingers_primarymon.zip)

**Comment by glenmurphy** [comment]
Marking as fixed as I got reports this works - thank you @guilbaults !
