### ISSUE TITLE
With Varjo Aero in VR don't move the cursor

### ISSUE THREAD

**Issue by J4P032** [glenmurphy/fingers#7]
Hello! 
I downloaded the latest version of the program and it works while I am off the VR world. In the VR Desktop that has Varjo the cursor moves with my hands. maybe is something related to varjo.
To let you test, you can install and use the developer tools even don't have the Varjo headset:
https://developer.varjo.com/docs/get-started/developer-tools-in-varjo-base

Also I notice that I have 2 screens with a full resolution in nvidia surround of 7680x2160 and the cursor moves only a portion of the big desktop resolution.
Thanks!

**Comment by J4P032** [comment]
Ok.. don't know what I did.. but now it is working. So you can close this case. Sorry

**Comment by glenmurphy** [comment]
Thanks for the report though - if it comes back would love to figure out why
